#!/usr/bin/env sh

# Helper
alias urlencode='python3 -c "import sys, urllib.parse as ul; print (ul.quote_plus(input()))"'

# Variables
export BINDER_URL="https://mybinder.org/v2/git/`git config --get remote.origin.url | urlencode`/HEAD"
export GENERATE_URL="`git config --get remote.origin.url`/generate"
export DATE_STRING="`date +'%Y-%m-%d %r %Z'`"

# Start the README with a warning message that it's machine generated
cat > README.md <<- END
<!-- This file is automatically generated! -->
<!-- Do not manually edit! To make changes, edit build_readme.md instead. -->

END

# Fill the rest of the README using a template
envsubst < build_readme.md >> README.md
